#pragma once

#define TAPPING_TERM 100
//#define PERMISSIVE_HOLD
#define PREVENT_STUCK_MODIFIERS

//#define STM32_SYSCLK KINETIS_SYSCLK_FREQUENCY
//#define NOP_FUDGE 0.4
//#define RGB_DI_PIN LINE_PIN28
//#define RGBLED_NUM 4
//#define RGBLIGHT_ANIMATIONS